[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'
hook_source = '''
nnoremap <Leader>hb :tabe <Bar>terminal stack build <CR>
nnoremap <Leader>hg :tabe <Bar>terminal stack ghci <CR>
nnoremap <Leader>ht :tabe <Bar>terminal stack test <CR>
nnoremap <Leader>hi :GhcModInfo <CR>
nnoremap <Leader>hy :GhcModType <CR>
'''

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
hook_source = '''
" let g:necoghc_debug = 1  " Enable to debug plugin
let g:haskellmode_completion_ghc = 1
autocmd FileType haskell setlocal omnifunc=necoghc#omnifunc
let g:necoghc_enable_detailed_browse = 1
let g:haskell_tabular = 1
'''
