[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jxs', 'coffee']
hook_source = '''
nnoremap <Leader>ni :tabe <Bar>terminal npm install <CR>
nnoremap <Leader>nt :tabe <Bar> terminal npm test <CR>
nnoremap <Leader>nw :tabe <Bar> terminal npm test -- --watch <CR>
nnoremap <Leader>ns :tabe <Bar> terminal npm start <CR>

if filereadable(".eslintrc")
  let g:neomake_javascript_enabled_makers=['eslint']
elseif filereadable(".jshint")
  let g:neomake_javascript_enabled_makers=['jshint']
else
  let g:neomake_javascript_enabled_makers=['standard']
endif
'''


[[plugins]]
repo = 'mxw/vim-jsx'
depends = 'pangloss/vim-javascript'
hook_source = '''
let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript', 'javascript.jxs']
build = 'npm install -g tern'
hook_source = '''
" Use deoplete.
let g:tern_request_timeout = 1
let g:tern_show_signature_in_pum = '0'  " This do disable full signature type on autocomplete
'''

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript.jxs']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript', 'javascript.jxs']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'digitaltoad/vim-pug'
