[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx', 'coffee']
hook_source = '''
nnoremap <Leader>ni :Dispatch npm install <CR>
nnoremap <Leader>nt :Dispatch npm test <CR>
nnoremap <Leader>nw :Dispatch npm test -- --watch <CR>
nnoremap <Leader>ns :Dispatch npm start <CR>
'''

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'mxw/vim-jsx'
depends = 'pangloss/vim-javascript'
hook_source = '''
let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'digitaltoad/vim-pug'
