hook_add = '''
" Behavior settings
set nocompatible      " Vim behavior, not Vi.
set nobackup         " Don't backup
set nowritebackup    " Write file in place
set noswapfile       " Don't use swap files (.swp)
set autoread         " Autoreload buffers
set autowrite        " Automatically save changes before switching buffers
set shell=zsh        " Same shell I normally use
set showcmd          " Display incomplete commands
set visualbell       " Use visual bell instead of audible bell
set backspace=2      " Backspace works like other apps
set timeoutlen=1000  " Timeout for key mapping combos
set ttimeoutlen=1000 " Timeout for key code combos
set mouse=a          " Use mouse
set updatetime=250   " Time before plugins do stuff

" Better Split Navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <bs> <C-W><C-H> " Fix <C-H> in neovim
nnoremap <C-H> <C-W><C-H>

" Neovim escape key fix
tnoremap <ESC> <C-\><C-n>

" Open splits to the right and below
set splitright
set splitbelow

" Find Replace current word
nnoremap <Leader>s :%s/\<<C-r><C-w>\>/

" Searching
set ignorecase     " Case insensitive search

" , to remove hightlighting
nmap <silent> , :nohlsearch<CR>

" Save file with sudo trick
cmap w!! w !sudo tee % >/dev/null
set smartcase      " Smarter Case insensitive search

" Skip the colon shortcuts
nnoremap <Leader>w :w<CR>
nnoremap <Leader>wq :wq<CR>
nnoremap <Leader>wQ :wq!<CR>
nnoremap <Leader>qa :qa<CR>
nnoremap <Leader>qq :q<CR>
nnoremap <Leader>qQ :q!<CR>
nnoremap <Leader>z <C-z>
nnoremap <Leader>e :e<CR>

" Quick Fix and Location Shortcuts
nnoremap <Leader>co :copen <CR>
nnoremap <Leader>cc :cclose <CR>
nnoremap <Leader>lo :lopen <CR>
nnoremap <Leader>lc :lclose <CR>

" Make dot work in visual mode
vnoremap . :norm.<CR>
'''
