hook_add = '''
" Display settings
set number            " Show current line number
set ruler             " Show curser position
set cursorline        " Highlight current cursor line
set cuc cul"          " Highlight active column
syntax on             " Syntax Highlighting

" highlight the 80th column
if exists('+colorcolumn')
  let &colorcolumn="180"
  highlight ColorColumn ctermbg=236
endif
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-scripts/L9'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
colorscheme solarized
set background=dark   " Dark background style
set spell
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
set laststatus=2                  " Always show status line
let g:airline_powerline_fonts = 1 " Use powerline fonts in airline
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_theme='solarized'
'''

hook_add = '''
" Add mappings first, since they will trigger loading NERDTree plugin
map <Leader>n :NERDTreeToggle<CR>
map <Leader>f :NERDTreeFind<CR>
" Load NERDTree when opening vim with no file or with just directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | wincmd p | ene | exe 'NERDTree' argv()[0] | endif
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle', 'NERDTreeFind', 'NERDTree']
hook_source = '''
  let g:NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-vinegar'
hook_add = '''
map _ :e .<CR>
'''
