hook_add = '''
" Behavior settings
set nocompatible      " Vim behavior, not Vi.
set nobackup         " Don't backup
set nowritebackup    " Write file in place
set noswapfile       " Don't use swap files (.swp)
set autoread         " Autoreload buffers
set autowrite        " Automatically save changes before switching buffers
set shell=zsh        " Same shell I normally use
set showcmd          " Display incomplete commands
set visualbell       " Use visual bell instead of audible bell
set backspace=2      " Backspace works like other apps
set timeoutlen=350   " Timeout for key combos
set mouse=a          " Use mouse
set updatetime=250   " Time before plugins do stuff

" Tabs and spaces
set tabstop=2         " Tabs are 2 spaces
set shiftwidth=2      " 2 Spaces for << && >>
set softtabstop=2     " Tabs are 2 spaces for editing operations
set expandtab         " Always use spaces instead of tabs
set smartindent       " Auto indent
set nowrap            " Don't wrap lines
map <F7> mzgg=G`z     " F7 to format file

" Show whitespaces
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.
autocmd filetype html,xml,java set listchars-=tab:>.

" Better Split Navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <bs> <C-W><C-H> " Fix <C-H> in neovim
nnoremap <C-H> <C-W><C-H>

" Neovim escape key fix
tnoremap <ESC> <C-\><C-n>

" Open splits to the right and below
set splitright
set splitbelow

" Find Replace current word
nnoremap <Leader>s :%s/\<<C-r><C-w>\>/

" Searching
set ignorecase     " Case insensitive search

" Don't bother with shift
nnoremap ; :

" Navigate wraped lines with capitals
nnoremap J gj
nnoremap K gk

" , to remove hightlighting
nmap <silent> , :nohlsearch<CR>

" Save file with sudo trick
cmap w!! w !sudo tee % >/dev/null
set smartcase      " Smarter Case insensitive search

" Skip the colon shortcuts
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>wq :wq<CR>
nnoremap <Leader>qa :qa<CR>
nnoremap <Leader>z <C-z>
nnoremap <Leader>e :e<CR>

" Make dot work in visual mode
vnoremap . :norm.<CR>

" Have the indent commands re-highlight the last visual selection to make multiple indentations easier
vnoremap > >gv
vnoremap < <gv

" Manual folding with zf, za
set foldmethod=manual
'''
